{
 "title": "Quick Facts",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  }
 ]
}
{
 "title": "I/O Overview",
 "panels": [
  {
   "title": "Rate",
   "type": "graph",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[1m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threads_busy_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "TOMCAT - BSY"
    },
    {
     "expr": "tomcat_threads_current_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "TOMCAT - CUR"
    },
    {
     "expr": "tomcat_threads_config_max_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "TOMCAT - MAX"
    },
    {
     "expr": "jetty_threads_busy{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JETTY - BSY"
    },
    {
     "expr": "jetty_threads_current{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JETTY - CUR"
    },
    {
     "expr": "jetty_threads_config_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JETTY - MAX"
    }
   ]
  }
 ]
}
{
 "title": "JVM Memory",
 "panels": [
  {
   "title": "JVM Heap",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Process Memory",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_memory_rss_bytes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_memory_swap_bytes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "process_memory_rss_bytes{application=\"$application\", instance=\"$instance\"} + process_memory_swap_bytes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "total"
    }
   ]
  }
 ]
}
{
 "title": "JVM Misc",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{application=\"$application\", instance=\"$instance\"}[15m])",
     "legendFormat": "process-15m"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "GC Pressure",
   "type": "graph",
   "description": "The percent of time spent on Garbage Collection over all CPUs assigned to the JVM process.",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])) by (application, instance) / on(application, instance) system_cpu_count",
     "legendFormat": "CPU time spent on GC"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "graph",
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}
{
 "title": "JVM Memory Pools (Heap)",
 "panels": [
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}
{
 "title": "JVM Memory Pools (Non-Heap)",
 "panels": [
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}
{
 "title": "Garbage Collection",
 "panels": [
  {
   "title": "Collections",
   "type": "graph",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])/rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "promoted"
    }
   ]
  }
 ]
}
{
 "title": "Classloading",
 "panels": [
  {
   "title": "Classes loaded",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{application=\"$application\",instance=\"$instance\"}[1m])",
     "legendFormat": "delta-1m"
    }
   ]
  }
 ]
}
{
 "title": "Buffer Pools",
 "panels": [
  {
   "title": "$jvm_buffer_pool",
   "type": "graph",
   "repeat": "jvm_buffer_pool",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "capacity"
    },
    {
     "expr": "jvm_buffer_count_buffers{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "buffers"
    }
   ]
  }
 ]
}
{
 "title": "Shop System — Service Metrics",
 "tags": [
  "shop",
  "gateway",
  "ping-service",
  "micrometer"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Business metrics — shop", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Orders Placed (rate/5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(shop_orders_placed_total[5m])",
     "legendFormat": "orders/sec"
    }
   ]
  },
  {
   "title": "Total Orders Placed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shop_orders_placed_total", "legendFormat": "total" }
   ]
  },
  {
   "title": "API Calls by Controller/Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (class, method) (rate(shop_api_calls_total[5m]))",
     "legendFormat": "{{class}}.{{method}}"
    }
   ]
  },
  {
   "title": "HTTP traffic — shop, gateway, ping-service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Request Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (application) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Error Rate by Service (4xx/5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (application) (rate(http_server_requests_seconds_count{status=~\"4..|5..\"}[1m]))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Average Latency by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (application) (rate(http_server_requests_seconds_sum[1m])) / sum by (application) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Max Latency by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (application) (http_server_requests_seconds_max)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Service internals — gateway, ping-service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Executor Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "executor_active_threads", "legendFormat": "{{application}}" }
   ]
  },
  {
   "title": "Executor Queued Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "executor_queued_tasks", "legendFormat": "{{application}}" }
   ]
  },
  {
   "title": "Gateway Configured Routes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_cloud_gateway_routes_count",
     "legendFormat": "routes"
    }
   ]
  }
 ]
}